# Generated by Django 3.2.7 on 2021-11-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='points',
            old_name='point_value',
            new_name='dollar_value',
        ),
        migrations.AddField(
            model_name='product',
            name='sponsored_by',
            field=models.ManyToManyField(to='catalog.SponsorOrg'),
        ),
    ]
