# Generated by Django 3.2.7 on 2021-11-27 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20211126_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='status',
        ),
    ]
