# Generated by Django 3.2.7 on 2021-11-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_apply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apply',
            name='reason',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
