# Generated by Django 3.2.7 on 2021-11-27 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20211127_1135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apply',
            new_name='Application',
        ),
    ]
