# Generated by Django 3.2.7 on 2021-11-27 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_rename_sponsor_driver_sponsors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='sponsors',
            new_name='sponsor',
        ),
    ]
