# Generated by Django 3.2.7 on 2021-11-28 02:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_point_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsororg',
            name='point_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator('0.01')]),
        ),
    ]
