# Generated by Django 3.2.7 on 2021-11-28 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_sponsororg_point_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point_update',
            name='points_total_value',
        ),
    ]
