# Generated by Django 3.2.7 on 2021-11-28 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_remove_point_update_points_total_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='point_update',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.point', to_field='sponsor_org'),
        ),
        migrations.AlterField(
            model_name='point',
            name='point_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
