# Generated by Django 3.2.7 on 2021-11-28 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20211128_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='sponsor_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.sponsororg'),
        ),
        migrations.AlterField(
            model_name='point_update',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.sponsororg'),
        ),
    ]
