# Generated by Django 3.2.7 on 2021-11-28 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20211128_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsororg',
            name='point_value',
            field=models.DecimalField(decimal_places=2, default='.01', max_digits=5, validators=[django.core.validators.MinValueValidator('0.01')]),
        ),
    ]
