# Generated by Django 3.2.7 on 2021-11-28 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_sponsororg_point_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='point_value',
        ),
        migrations.AlterField(
            model_name='sponsororg',
            name='point_value',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
