# Generated by Django 3.2.7 on 2021-11-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20211128_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='point_update',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
