# Generated by Django 3.2.7 on 2021-11-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_point_update_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='monetary_value',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=7),
        ),
    ]
